# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_auto_20161112_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='create_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
