# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.CharField(max_length=500),
        ),
    ]
