# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='now',
            field=models.DateField(auto_now=True),
        ),
    ]
