# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_comment_now'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='now',
            new_name='date',
        ),
        migrations.AddField(
            model_name='comment',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
