# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_userprofile_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.FileField(default='http://semantic-ui.com/images/avatar/small/elliot.jpg', upload_to='profile_image'),
        ),
    ]
