# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20161217_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='authorOrNot',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='choices',
            field=models.CharField(choices=[('author', 'author'), ('normal', 'normal')], default='normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(default='maomao', max_length=100),
        ),
    ]
