# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_auto_20161112_0442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='createtime',
        ),
        migrations.AddField(
            model_name='comment',
            name='avater',
            field=models.CharField(blank=True, default='static/images/default.png', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='creatdate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
