# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_auto_20170210_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='creatdate',
            field=models.DateField(auto_now=True),
        ),
    ]
