# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_auto_20170210_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='creattime',
            field=models.TimeField(auto_now=True),
        ),
    ]
